# -*- coding: utf-8 -*-
"""Untitled24.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nCwzXFzkzcJFgiytnJW2AE2vgVMsByiQ
"""

import streamlit as st
import requests
from bs4 import BeautifulSoup

st.title("🌐 Simple Web Scraper")

# Input box for user to enter URL
url = st.text_input("https://realpython.com/beautiful-soup-web-scraper-python/")

if url:
    try:
        # Fetch the page
        response = requests.get(url)
        response.raise_for_status()  # check for errors

        # Parse with BeautifulSoup
        soup = BeautifulSoup(response.text, "html.parser")

        # Extract title
        title = soup.title.string if soup.title else "No title found"

        st.success(f"✅ Title of the page: {title}")

    except Exception as e:
        st.error(f"❌ Error: {e}")

